#修改tomcat的版本号
server:
  port: 8080
# MySQL数据库连接配置
spring:
  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/smk?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  mvc:
    view:
      prefix: /page/
      suffix: .jsp

#开启驼峰命名匹配映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #配置MyBatis的xml配置文件路径
  mapper-locations: classpath:mapper/*.xml
  #配置XML映射文件中指定的实体类别名路径
  type-aliases-package: com.imp.pojo



